for i = 1:999
    if ~(isfile(sprintf('WSNN_1000/all_probes_28/BC_%s_seq.txt',num2str(i,'%03.f'))))
        findprobesLocal(sprintf('WSNN_1000/all_fastas/BC_%s.fasta',num2str(i,'%03.f')), ...
        32, ...
        'oligolength',28, ...
        'allowableGibbsFE', [-36,-30], ...
        'targetGibbsFE', -33, ...
        'outfilename',sprintf('WSNN_1000/all_probes_28/BC_%s',num2str(i,'%03.f')))
    end
end