parfor i = 1:500
    findprobesLocal(sprintf('NNNSW_700/all_fastas/BC_%s.fasta',num2str(i,'%03.f')), ...
        32, ...
        'oligolength',28, ...
        'allowableGibbsFE', [-36,-30], ...
        'targetGibbsFE', -33, ...
        'outfilename',sprintf('NNNSW_700/all_probes_28/BC_%s',num2str(i,'%03.f')))
end